// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// myfunctor
Rcpp::NumericVector myfunctor(Rcpp::NumericVector x);
RcppExport SEXP RcppThrust_myfunctor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(myfunctor(x));
    return rcpp_result_gen;
END_RCPP
}
// mysort
Rcpp::NumericVector mysort(Rcpp::NumericVector x);
RcppExport SEXP RcppThrust_mysort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mysort(x));
    return rcpp_result_gen;
END_RCPP
}
