# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myfunctor <- function(x) {
    .Call('RcppThrust_myfunctor', PACKAGE = 'RcppThrust', x)
}

mysort <- function(x) {
    .Call('RcppThrust_mysort', PACKAGE = 'RcppThrust', x)
}

